services:
  pg:
    image: postgres:16-alpine
    hostname: pg
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: postgres
      POSTGRES_DB: memowords
    volumes:
      - memowords-pg-data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
      ACCESS_TOKEN_SECRET: "${ACCESS_TOKEN_SECRET}"
      DB_HOST: pg
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: "${POSTGRES_PASSWORD}"
      DB_DATABASE: memowords
    depends_on:
      - pg
volumes:
  memowords-pg-data:
    external: true
