services:
  pg:
    image: postgres:16-alpine
    hostname: pg
    networks:
      - default
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: postgres
      POSTGRES_DB: memowords
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - memowords-pg-data:/var/lib/postgresql/data
  app:
    image: memowords_app:latest
    hostname: memowords-entrypoint
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.memowords.entrypoints=websecure"
      - "traefik.http.routers.memowords.rule=Host(`memowords.dmku.dev`)"
      - "traefik.http.routers.memowords.tls.certresolver=gcloud"
    networks:
      - default
      - memowords
    environment:
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
      ACCESS_TOKEN_SECRET: "${ACCESS_TOKEN_SECRET}"
      DB_HOST: pg
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: "${POSTGRES_PASSWORD}"
      DB_DATABASE: memowords
    depends_on:
      pg:
        condition: service_healthy
volumes:
  memowords-pg-data:
    external: true
networks:
  default:
  memowords:
    external: true
